Dtrace=function(A,B){
  A=t(A)/2+A/2
  B=t(B)/2+B/2
  fit=matrixEigen(A)
  U=fit$vectors
  D=fit$values
  p=length(A[,1])
  D1=rep(D,p);D1=matrix(D1,p,p)
  C1=2/(D1+t(D1))
  G=matrixListProduct(list(t(U),B,U))*C1
  E=matrixListProduct(list(U,G,t(U)))
  return(E)
}
